name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    uses: ShawnDen-coder/repo-scaffold/.github/workflows/reusable-rust-ci.yaml@0.30.0
    with:
      rust-toolchain: stable
      test-container: {{ 'true' if cookiecutter.use_docker == 'yes' else 'false' }}
      containerfile: ./container/Dockerfile
