name: 🚀 Release Build & Publish

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

jobs:
  release:
    uses: ShawnDen-coder/repo-scaffold/.github/workflows/reusable-rust-release.yaml@0.30.0
    with:
      {% raw %}tag: ${{ github.ref_name }}{% endraw %}
      crate-name: {{ cookiecutter.crate_name }}
      publish-crates: true
      publish-container: {{ 'true' if cookiecutter.use_docker == 'yes' else 'false' }}
      containerfile: ./container/Dockerfile
    secrets:
      {% raw %}CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}{% endraw %}
