name: 📚 Deploy Documentation
on:
  workflow_call:
    inputs:
      tag:
        description: Existing global release tag to deploy
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: Existing global release tag to deploy
        required: true
        type: string
jobs:
  deploy:
    uses: ShawnDen-coder/repo-scaffold/.github/workflows/reusable-docs-deploy.yaml@0.27.0
    with:
      {% raw %}tag: ${{ inputs.tag }}{% endraw %}
    secrets:
      {% raw %}PYPI_SERVER_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
      PYPI_SERVER_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}{% endraw %}
