name: 🚀 Release Build & Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      {% raw %}UV_INDEX_HOMELAB_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
      UV_INDEX_HOMELAB_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}
      PYPI_SERVER_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
      PYPI_SERVER_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}{% endraw %}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: init environment and test
        run: |
          uvx --from rust-just just init
          uvx --from rust-just just lint
      - name: Run tests
        run: uvx --from rust-just just test-all

  publish-pypi:
    needs: test
    runs-on: ubuntu-latest
    if: vars.PUBLISH_TO_PUBLIC_PYPI == 'true'
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build package
        run: uvx --from rust-just just build
      - name: Publish to PyPI
        env:
          {% raw %}UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}{% endraw %}
        run: uvx --from rust-just just publish-pypi

  publish-private-pypi:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      {% raw %}UV_INDEX_HOMELAB_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
      UV_INDEX_HOMELAB_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}
      PYPI_SERVER_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
      PYPI_SERVER_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}{% endraw %}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build and publish to PyPI Server
        run: uvx --from rust-just just deploy-pypi-server

  release:
    needs: [test, publish-private-pypi, publish-pypi]
    {% raw %}if: |
      ${{ always() &&
      needs.test.result == 'success' &&
      needs.publish-private-pypi.result == 'success' &&
      (needs.publish-pypi.result == 'success' || needs.publish-pypi.result == 'skipped') }}{% endraw %}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build package for release
        run: uvx --from rust-just just build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          {% raw %}tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}{% endraw %}
          files: |
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true
        env:
          {% raw %}GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
