name: ✅ Code Quality & Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}{% endraw %}
jobs:
  ci:
    uses: ShawnDen-coder/repo-scaffold/.github/workflows/reusable-python-ci.yaml@0.27.0
    with:
      python-versions: '[{% set min_minor = cookiecutter.min_python_version.split('.')[1]|int %}{% set max_minor = cookiecutter.max_python_version.split('.')[1]|int %}{% for minor in range(min_minor, max_minor + 1) %}"3.{{ minor }}"{% if not loop.last %}, {% endif %}{% endfor %}]'
      workspace: false
      test-container: {{ 'true' if cookiecutter.use_podman == 'yes' else 'false' }}
    secrets:
      {% raw %}PYPI_SERVER_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
      PYPI_SERVER_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}{% endraw %}
