name: release_build

on:
  push:
    tags:
      - '*'  # 匹配所有标签
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 1.0.0)'
        required: true
        type: string

permissions:
  contents: write  # 用于创建 release
  id-token: write  # 用于发布到 PyPI

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      install-deps: dev
      python-version: "{{ cookiecutter.max_python_version }}"
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    outputs:
      personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: uvx nox -s test_all

      - name: Build package
        run: uvx nox -s build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ needs.setup.outputs.PERSONAL_ACCESS_TOKEN || github.token }}
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://upload.pypi.org/legacy/
