ignore_merge_commits = true
branch_whitelist = ["master", "main"]
skip_ci = "[skip ci]"

pre_bump_hooks = [
    "echo 'bumping from {% raw %}{{latest|0.0.0}}{% endraw %} to {% raw %}{{version|0.0.1}}{% endraw %}'",
    "uv version {% raw %}{{version|0.0.1}}{% endraw %}",
    "uv lock --no-upgrade",
]

post_bump_hooks = [
    "git push",
    "git push origin {% raw %}{{version}}{% endraw %}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "{{cookiecutter.github_username}}"
repository = "{{cookiecutter.project_slug}}"
