name: Deploy Docs

on:
  push:
    tags:
      - '*'  # 匹配所有标签
  workflow_dispatch:  # 保留手动触发选项

permissions:
  contents: write  # 用于部署到 GitHub Pages

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      install-deps: docs
    secrets: inherit

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy documentation
        run: uv run mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ github.token }}
