name: 🚀 Release Build & Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
  id-token: write
jobs:
  release:
    uses: ShawnDen-coder/repo-scaffold/.github/workflows/reusable-python-release.yaml@0.27.0
    with:
      tag: ${{ github.ref_name }}
      workspace: false
      deploy-docs: false
    secrets: inherit
